# Generated by Django 5.1.2 on 2024-12-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_customuser_address_customuser_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
